// <auto-generated />
using System;
using AccessData.DataBaseInfraestructure.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccessData.Migrations
{
    [DbContext(typeof(RetailStoreDBContext))]
    [Migration("20240330052958_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccessData.DataBaseInfraestructure.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Electrodomésticos"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Tecnología_y_Electrónica"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Moda_y_Accesorios"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Hogar_y_Decoración"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Salud_y_Belleza"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Deportes_y_Ocio"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Juguetes_y_Juegos"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Alimentos_y_Bebidas"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Libros_y_Material_Educativo"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Jardinería_y_Bricolaje"
                        });
                });

            modelBuilder.Entity("AccessData.DataBaseInfraestructure.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("ImageLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("bd473544-c52b-4a63-b602-8240ba9b6b07"),
                            CategoryId = 1,
                            Description = "Disfrutá de tus alimentos frescos y almacenalos de manera práctica y cómoda en la heladera Drean, la protagonista de la cocina.",
                            Discount = 31,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_661063-MLU74118278062_012024-O.webp",
                            Name = "Heladera Drean HDR400F11 steel con freezer 396L 220V",
                            Price = 1298199m
                        },
                        new
                        {
                            ProductId = new Guid("71cc9a4c-f564-48b7-803d-5d5b3128b656"),
                            CategoryId = 1,
                            Description = "Únicamente necesita que se introduzcan los productos de limpieza y se elija el programa deseado.",
                            Discount = 39,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_944011-MLA74651986202_022024-O.webp",
                            Name = "Lavarropas automático Drean Next 8.14 P ECO inverter blanco 8kg 220 V",
                            Price = 744292m
                        },
                        new
                        {
                            ProductId = new Guid("d54add1b-882e-4cb7-84d3-3d0cbbf7cd9d"),
                            CategoryId = 1,
                            Description = "Marca líder mundial en la comercialización de electrodomésticos que orienta su trabajo en la tecnología, el diseño y la innovación para mejorar la calidad de vida.",
                            Discount = 47,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_973805-MLU74159511409_012024-O.webp",
                            Name = "Lavavajilla Drean Dish 12.2 Ltx 12 Cubiertos Acero",
                            Price = 1209224m
                        },
                        new
                        {
                            ProductId = new Guid("6177471d-978f-4b96-b14c-547dd5cfd74f"),
                            CategoryId = 1,
                            Description = "Freidora de Aire Gadnic F4.0 Sin Aceite 4Lts Digital",
                            Discount = 0,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_862380-MLU74244415875_012024-O.webp",
                            Name = "Freidora Eléctrica De Aire Sin Aceite + Pinza Gratis 1400w Color Negro",
                            Price = 124999m
                        },
                        new
                        {
                            ProductId = new Guid("73538e3d-a76f-4c31-8211-00c3f7224c22"),
                            CategoryId = 2,
                            Description = "El Robot de limpieza ATMA facilita la tarea de mantener los pisos impecables, combinando las funciones de aspirar y trapear simultáneamente.",
                            Discount = 19,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_898750-MLU73587878148_122023-O.webp",
                            Name = "Aspiradora Trapeadora Robot Atma Atar21c1dh Blanca 220v",
                            Price = 668249m
                        },
                        new
                        {
                            ProductId = new Guid("58bc191e-49eb-4c2f-8c65-f304148e789e"),
                            CategoryId = 2,
                            Description = "Con tu consola Switch tendrás entretenimiento asegurado todos los días. Su tecnología fue creada para poner nuevos retos tanto a jugadores principiantes como expertos. ",
                            Discount = 0,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_803086-MLA47920649105_102021-O.webp",
                            Name = "Nintendo Switch OLED 64GB Standard color rojo neón, azul neón y negro",
                            Price = 517999m
                        },
                        new
                        {
                            ProductId = new Guid("5780c0f8-5c24-4f2a-9347-4ac818e4b5c4"),
                            CategoryId = 2,
                            Description = "Cargador Móvil Gadnic con LED Indicador de Batería 25000 mAh",
                            Discount = 0,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_639848-MLU73345299871_122023-O.webp",
                            Name = "Cargador Móvil Gadnic Con Lde Indicador De Batería 25000 Mah Color Negro",
                            Price = 41749m
                        },
                        new
                        {
                            ProductId = new Guid("cae0ac0f-4b96-4c47-86ca-1e23a6db3072"),
                            CategoryId = 2,
                            Description = "Google TV de Philips le ofrece el contenido que desea, cuando lo desee. Puede personalizar su pantalla principal para mostrar sus aplicaciones favoritas.",
                            Discount = 11,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_677196-MLU74154724021_012024-O.webp",
                            Name = "Tv Smart Led Philips 32 Hd 32phd6918/77 Google Tv",
                            Price = 269999m
                        },
                        new
                        {
                            ProductId = new Guid("8257a1e7-fa7b-483f-8856-ec598f318f4c"),
                            CategoryId = 3,
                            Description = "PULSERA DE ACERO QUIRURGICO 2 EN 1",
                            Discount = 0,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_727752-MLA47723827894_102021-O.webp",
                            Name = "Combo Pulsera Hombre 2 En 1 Acero Quirugico Inoxidable Pack",
                            Price = 2547.25m
                        },
                        new
                        {
                            ProductId = new Guid("eecbb9df-336d-482d-a73f-722970be11b8"),
                            CategoryId = 3,
                            Description = "Shoter premium shoe cleaner es un producto innovador para la limpieza de calzado urbano y deportivo.",
                            Discount = 0,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_659147-MLA40000388003_122019-O.webp",
                            Name = "Limpia Zapatillas Shoter - Kit (limpiador Premium + Cepillo)",
                            Price = 18400m
                        },
                        new
                        {
                            ProductId = new Guid("71d82d74-f337-48d7-892b-8b9faa23e02d"),
                            CategoryId = 3,
                            Description = "PANTALON CARGO JOGGER 4 BOLSILLOS Y 2 SOLAPAS TRASERAS DE GABARDINA.",
                            Discount = 10,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_964819-MLA70940869495_082023-O.webp",
                            Name = "Pantalones Hombre Cargo Gabardina Bolsillos Casuales Jogger",
                            Price = 21899m
                        },
                        new
                        {
                            ProductId = new Guid("f9b64fba-450a-409e-ada7-a2436bf5bcee"),
                            CategoryId = 3,
                            Description = "Bolso Wilson 65.150005.",
                            Discount = 11,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_910443-MLU72877827774_112023-O.webp",
                            Name = "Bolso Wilson Deportivo Viaje Urbano Bolsillo Gimnasio Cierre Color Verde Liso",
                            Price = 39999m
                        },
                        new
                        {
                            ProductId = new Guid("68967c6e-093f-45f1-85b9-1dfb3c28e069"),
                            CategoryId = 4,
                            Description = "Pileta Encastrable HARDEST Modelo HQ-113XT.",
                            Discount = 0,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_760812-MLA54507511656_032023-O.webp",
                            Name = "Bacha Cocina Pileta Simple Acero Inoxidable Dosificador 56cm",
                            Price = 102999m
                        },
                        new
                        {
                            ProductId = new Guid("078fda86-273f-459e-9d77-90f6beda2dbf"),
                            CategoryId = 4,
                            Description = "TENDER DE PIE ACERO CON ALAS.",
                            Discount = 15,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_685369-MLU72549946435_102023-O.webp",
                            Name = "Tendedero Tender Ropa Alas Acero Pintado Plegable De Pie 953 Color Blanco",
                            Price = 16341.18m
                        },
                        new
                        {
                            ProductId = new Guid("69e33cba-ae20-4865-91c1-2bb9998095af"),
                            CategoryId = 4,
                            Description = "Cuadro moderno decorativo calado sobre madera mdf ideal para hogar casa oficina living ambientes minimalistas degrade.",
                            Discount = 5,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_937605-MLU71497717015_092023-O.webp",
                            Name = "Cuadro Madera Calado Mdf 5 Hojas Moderno Living Decorativo Color Degrade",
                            Price = 13999m
                        },
                        new
                        {
                            ProductId = new Guid("7b2109c9-6dfe-4a2a-b934-1c8ebed0253f"),
                            CategoryId = 4,
                            Description = "Cortina Guirnalda Estrellas Luz Led Cálida Amarilla Efectos.",
                            Discount = 67,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_817788-MLA73104183943_112023-O.webp",
                            Name = "Cortina Guirnalda Estrellas Luz Led Calida Amarilla Efectos",
                            Price = 29000m
                        },
                        new
                        {
                            ProductId = new Guid("69a710b8-4da3-4b23-812b-5120570d88cc"),
                            CategoryId = 5,
                            Description = "Bienvenido a la tienda oficial de SanCor Bebé, donde podés comprar todos nuestros productos directo de fábrica, pagarlos online y recibirlos donde quieras de forma segura y confiable.",
                            Discount = 0,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_808805-MLA51087990624_082022-O.webp",
                            Name = "Biogaia Gotas Probioticas Suplemento Dietario X 5 Ml",
                            Price = 25814m
                        },
                        new
                        {
                            ProductId = new Guid("db1ead2f-9100-4dfd-9d30-cd23a7005ee4"),
                            CategoryId = 5,
                            Description = "El Aspirador Nasal Asistido Nuby es el aliado perfecto para cuidar la salud de tu bebé desde los primeros meses de vida.",
                            Discount = 0,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_661607-MLU72831502725_112023-O.webp",
                            Name = "Nuby Aspirador Nasal Asistido Con Boquilla Y Filtro Color Transparente",
                            Price = 12516m
                        },
                        new
                        {
                            ProductId = new Guid("6c072b35-4ab3-4e34-9a76-f509d6d5420f"),
                            CategoryId = 5,
                            Description = "KIT DE CUIDADO FACIAL COMPLETO.",
                            Discount = 0,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_614555-MLA48554874576_122021-O.webp",
                            Name = "Kit Limpieza Cuidado Facial Belleza Mascarilla Cepillo",
                            Price = 22999m
                        },
                        new
                        {
                            ProductId = new Guid("7e6b9b97-6a84-41cc-9e44-6f7c42045aab"),
                            CategoryId = 5,
                            Description = "Contenido 7gr",
                            Discount = 0,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_825714-MLU72831156837_112023-O.webp",
                            Name = "Corrector De Ojereas Artez Westerley Distr. Oficial",
                            Price = 7900m
                        },
                        new
                        {
                            ProductId = new Guid("d917cd42-3cc2-41b1-be4e-f4452e52adef"),
                            CategoryId = 6,
                            Description = "Adidas Argentum 19.",
                            Discount = 0,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_961577-MLA74277409609_012024-O.webp",
                            Name = "Pelota adidas Argentum 19 Liga Argentina Balón Oficial",
                            Price = 140000m
                        },
                        new
                        {
                            ProductId = new Guid("e260a99d-59d2-4e44-a977-5f8fd318db0c"),
                            CategoryId = 6,
                            Description = "GUANTE ATTRAKT SOLID.",
                            Discount = 0,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_737373-MLA69694206154_052023-O.webp",
                            Name = "Guante Arquero Attrakt Solid Reusch Exclusivo",
                            Price = 43230m
                        },
                        new
                        {
                            ProductId = new Guid("4c730b0a-adea-4f23-b7f7-37f5cec25918"),
                            CategoryId = 6,
                            Description = "Edad recomendada: de 8 años a 120 años.",
                            Discount = 0,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_655528-MLU74053078727_012024-O.webp",
                            Name = "Destroza Este Diario Color - Keri Smith - Libro Del Fondo",
                            Price = 20200m
                        },
                        new
                        {
                            ProductId = new Guid("34685fdc-f168-415e-800e-e3136be1f37a"),
                            CategoryId = 6,
                            Description = "Soga de saltar de acero Speed Rope.",
                            Discount = 19,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_783722-MLA70257450564_072023-O.webp",
                            Name = "Soga Para Saltar Aluminio Rulemanes/ Boxeo Fitness Crossfit",
                            Price = 14998m
                        },
                        new
                        {
                            ProductId = new Guid("4bd6a03b-b9b1-4333-b690-a81ad54c7ecb"),
                            CategoryId = 7,
                            Description = "Helicóptero Dron Inteligente Sensorial Vuela Sube Y Baja.",
                            Discount = 316,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_716599-MLU73126252000_122023-O.webp",
                            Name = "Helicóptero Dron Inteligente Sensorial Vuela Sube Y Baja Color Negro",
                            Price = 17990m
                        },
                        new
                        {
                            ProductId = new Guid("657ea7e9-d214-4f80-8d7f-dca42aec9b0f"),
                            CategoryId = 7,
                            Description = "Cocina para nenas nenes chicos infantil madera.",
                            Discount = 5,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_611047-MLU74163663259_012024-O.webp",
                            Name = "Cocinita De Juguete Cocina Madera Infantil Juego Niños Niñas Color Marrón",
                            Price = 34999m
                        },
                        new
                        {
                            ProductId = new Guid("9bb43850-dc46-4705-8ecb-5083a287356d"),
                            CategoryId = 7,
                            Description = "En sus distintas ediciones, la franquicia de Super Mario ha logrado combinar su estilo con modernos modos de juego que divierten y desafían constantemente a quienes juegan.",
                            Discount = 0,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_764820-MLU70610438351_072023-O.webp",
                            Name = "Super Mario Bros Wonder Nintendo Switch",
                            Price = 82999m
                        },
                        new
                        {
                            ProductId = new Guid("8a640c7f-e29b-49f7-9c98-437ad1011d72"),
                            CategoryId = 7,
                            Description = "Con este juego de Mario vas a disfrutar de horas de diversión y de nuevos desafíos que te permitirán mejorar como gamer.",
                            Discount = 0,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_740157-MLU72836514627_112023-O.webp",
                            Name = "Super Mario Odyssey Super Mario Standard Edition Nintendo Switch Físico",
                            Price = 79206m
                        },
                        new
                        {
                            ProductId = new Guid("3f2f839b-61e1-4ae8-9916-9483b71e5550"),
                            CategoryId = 8,
                            Description = "Tableta Milka Chocolate Biscuit 300 gr",
                            Discount = 0,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_740928-MLA74220113425_012024-O.webp",
                            Name = "Tableta Milka Chocolate Biscuit 300 gr",
                            Price = 9999m
                        },
                        new
                        {
                            ProductId = new Guid("b6f37c6b-e827-4cb8-ae2c-77a9f1fb531e"),
                            CategoryId = 8,
                            Description = "Pack de 6 latas de 354 mL cada una.",
                            Discount = 0,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_878966-MLU73885793875_012024-O.webp",
                            Name = "Lata De Pepsi Cola Gaseosa X 354ml Pack X6 Und",
                            Price = 4381.82m
                        },
                        new
                        {
                            ProductId = new Guid("d63149b4-63cd-4b71-95c2-b49ca7f32d8a"),
                            CategoryId = 8,
                            Description = "Coca Cola Lata 354ml Original Gaseosa Pack X6 Latas.",
                            Discount = 5,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_790516-MLU72637348139_112023-O.webp",
                            Name = "Coca Cola Lata 354ml Original Gaseosa Pack X6 Latas",
                            Price = 9005.29m
                        },
                        new
                        {
                            ProductId = new Guid("52f8b197-81a9-4be8-8288-97fb7d2505f9"),
                            CategoryId = 8,
                            Description = "Milka Chocolate Oreo Max X 300 Gr.",
                            Discount = 0,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_816357-MLA74049228146_012024-O.webp",
                            Name = "Milka Chocolate Oreo Max X 300 Gr",
                            Price = 9999m
                        },
                        new
                        {
                            ProductId = new Guid("df4028e0-72f0-4095-9929-29a0128a1efc"),
                            CategoryId = 9,
                            Description = "Libro Hábitos Atómicos - James Clear - Booket.",
                            Discount = 0,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_673885-MLA54040457764_022023-O.webp",
                            Name = "Libro Hábitos Atómicos - James Clear - Booket",
                            Price = 14600m
                        },
                        new
                        {
                            ProductId = new Guid("6562dacf-0aa1-4eb7-b7e4-cc60af2a3c45"),
                            CategoryId = 9,
                            Description = "EL DUELO (BOLSILLO) - Gabriel Rolón.",
                            Discount = 10,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_869330-MLU73121803273_112023-O.webp",
                            Name = "Libro El duelo - Gabriel Rolón - Booket",
                            Price = 16000m
                        },
                        new
                        {
                            ProductId = new Guid("dacbe5ae-727c-4b6e-8103-4b52f9ee0b15"),
                            CategoryId = 9,
                            Description = "Expedicion Matematica 6 - Claudia Broitman.",
                            Discount = 5,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_800174-MLU73415445799_122023-O.webp",
                            Name = "Expedicion Matematica 6 - Claudia Broitman",
                            Price = 16700m
                        },
                        new
                        {
                            ProductId = new Guid("00ea931e-ea6b-49be-85e6-2628bd34d7bf"),
                            CategoryId = 9,
                            Description = "Como imposible y como quimera, como fin y también como imperativo, la idea de la felicidad nos interpela más que nunca en los tiempos que corren. “¿Cómo ser felices?”.",
                            Discount = 0,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_758457-MLU75135654463_032024-O.webp",
                            Name = "Libro La Felicidad - Gabriel Rolón - Planeta",
                            Price = 17990m
                        },
                        new
                        {
                            ProductId = new Guid("831ef33e-ec16-4b28-a0b1-142fccb10b8c"),
                            CategoryId = 10,
                            Description = "Sustrato Growmix 80Lts Multipro.",
                            Discount = 5,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_817546-MLU75142995540_032024-O.webp",
                            Name = "GrowMix Profesional Multipro 80L",
                            Price = 19860m
                        },
                        new
                        {
                            ProductId = new Guid("21c40cf8-2c30-4958-a12a-f58b944191b9"),
                            CategoryId = 10,
                            Description = "Mantener los espacios verdes de tu hogar ahora es más fácil, olvidate de cortes desprolijos y malezas.",
                            Discount = 36,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_643769-MLU71619277093_092023-O.webp",
                            Name = "Desmalezadora A Explosión 52cc Potencia 1500w 2 Hp DESMA52CC",
                            Price = 127110m
                        },
                        new
                        {
                            ProductId = new Guid("ae991287-bc7c-43fc-9e34-c203f378022f"),
                            CategoryId = 10,
                            Description = "Potencia: 80 W.",
                            Discount = 0,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_870740-MLU72833533367_112023-O.webp",
                            Name = "Pistola Encoladora 80 W Para Barras De Silicona De 11,2 Mm",
                            Price = 9888m
                        },
                        new
                        {
                            ProductId = new Guid("d12e9d46-b119-4368-8d1d-7f5e020ca23e"),
                            CategoryId = 10,
                            Description = "La cinta doble faz Universal tesa® es una cinta adhesiva de papel muy versátil, ideal para fijar alfombras, o para la decoración en casa y bricolaje.",
                            Discount = 0,
                            ImageLink = "https://http2.mlstatic.com/D_NQ_NP_860188-MLA47568116839_092021-O.webp",
                            Name = "Cinta Doble Faz 50mm X 25m Pega Alfombra-bricolage Tesa Tape",
                            Price = 12000m
                        });
                });

            modelBuilder.Entity("AccessData.DataBaseInfraestructure.Entities.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPay")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SaleId");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("AccessData.DataBaseInfraestructure.Entities.SaleProduct", b =>
                {
                    b.Property<int>("SaleProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleProductId"));

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("SaleId")
                        .HasColumnType("int");

                    b.HasKey("SaleProductId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleProduct");
                });

            modelBuilder.Entity("AccessData.DataBaseInfraestructure.Entities.Product", b =>
                {
                    b.HasOne("AccessData.DataBaseInfraestructure.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AccessData.DataBaseInfraestructure.Entities.SaleProduct", b =>
                {
                    b.HasOne("AccessData.DataBaseInfraestructure.Entities.Product", "Product")
                        .WithMany("SaleProduct")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccessData.DataBaseInfraestructure.Entities.Sale", null)
                        .WithMany("SaleProduct")
                        .HasForeignKey("SaleId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AccessData.DataBaseInfraestructure.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AccessData.DataBaseInfraestructure.Entities.Product", b =>
                {
                    b.Navigation("SaleProduct");
                });

            modelBuilder.Entity("AccessData.DataBaseInfraestructure.Entities.Sale", b =>
                {
                    b.Navigation("SaleProduct");
                });
#pragma warning restore 612, 618
        }
    }
}
